name = "MeasurementBrowser"
uuid = "12345678-1234-5678-9abc-123456789abc"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataAnalysis = "509f87cb-f238-4275-9ee2-d3327c3af205"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataLoader = "a8afec15-28fe-4831-94d8-4f8efdbf8782"
DataPlotter = "467e584f-0006-40b8-bc2d-8131653a99d4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SmoothData = "0112b07a-89eb-48f6-acf7-65d97704274c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CImGui = "6.1.0"
GLFW = "3.4.4"
GLMakie = "0.13.5"
ModernGL = "1.1.8"
PrecompileTools = "1.2.1"
Printf = "1.11.0"
SmoothData = "0.1.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
