name = "DataAnalysis"
uuid = "509f87cb-f238-4275-9ee2-d3327c3af205"
version = "0.1.0"
authors = ["Davide Lombardo <davide.lombardo@eit.lth.se>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SmoothData = "0112b07a-89eb-48f6-acf7-65d97704274c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataFrames = "1.8.1"
Dates = "1.11.0"
Printf = "1.11.0"
SmoothData = "0.1.0"
Statistics = "1.11.1"
